CREATE DATABASE HEYORANGE;
USE HEYORANGE;

CREATE TABLE `DOMINIO_STATUS_USUARIO` (
`ID` INT NOT NULL AUTO_INCREMENT,
`DESCRICAO` VARCHAR(100),
`FLAG_ATIVO` NUMERIC(1,0),
`NUMERO_ORDEM` INT,
PRIMARY KEY(`ID`)
);

CREATE TABLE `DOMINIO_TIPO_MENTORIA` (
`ID` INT NOT NULL AUTO_INCREMENT,
`DESCRICAO` VARCHAR(100),
`FLAG_ATIVO` NUMERIC(1,0),
`NUMERO_ORDEM` INT,
PRIMARY KEY(`ID`)
);

CREATE TABLE `DOMINIO_HABILIDADES` (
`ID` INT NOT NULL AUTO_INCREMENT,
`DESCRICAO` VARCHAR(100),
`FLAG_ATIVO` NUMERIC(1,0),
`NUMERO_ORDEM` INT,
PRIMARY KEY(`ID`)
);

CREATE TABLE `DOMINIO_TIPO_USUARIO` (
`ID` INT NOT NULL AUTO_INCREMENT,
`DESCRICAO` VARCHAR(100),
`FLAG_ATIVO` NUMERIC(1,0),
`NUMERO_ORDEM` INT,
PRIMARY KEY(`ID`)
);

CREATE TABLE `DOMINIO_NIVEL_EXPERIENCIA` (
`ID` INT NOT NULL AUTO_INCREMENT,
`DESCRICAO` VARCHAR(100),
`FLAG_ATIVO` NUMERIC(1,0),
`NUMERO_ORDEM` INT,
PRIMARY KEY(`ID`)
);

CREATE TABLE `DOMINIO_STATUS_MENTORIA` (
`ID` INT NOT NULL AUTO_INCREMENT,
`DESCRICAO` VARCHAR(100),
`FLAG_ATIVO` NUMERIC(1,0),
`NUMERO_ORDEM` INT,
PRIMARY KEY(`ID`)
);

CREATE TABLE `DOMINIO_TIPO_EMAIL` (
`ID` INT NOT NULL AUTO_INCREMENT,
`DESCRICAO` VARCHAR(100),
`FLAG_ATIVO` NUMERIC(1,0),
`NUMERO_ORDEM` INT,
PRIMARY KEY(`ID`)
);

CREATE TABLE `DOMINIO_TIPO_ACAO` (
`ID` INT NOT NULL AUTO_INCREMENT,
`DESCRICAO` VARCHAR(100),
`FLAG_ATIVO` NUMERIC(1,0),
`NUMERO_ORDEM` INT,
PRIMARY KEY(`ID`)
);

CREATE TABLE `HISTORICO` (
`ID` INT NOT NULL AUTO_INCREMENT,
`DATA_CRIACAO` TIMESTAMP,
`DATA_ALTERACAO` TIMESTAMP,
`USUARIO_CRIACAO` VARCHAR(100),
`USUARIO_ALTERACAO` VARCHAR(100),
`ID_DOMINIO_TIPO_ACAO` INT NOT NULL,
PRIMARY KEY(`ID`),
CONSTRAINT `FK_DOMINIO_TIPO_ACAO` FOREIGN KEY (`ID_DOMINIO_TIPO_ACAO`) 
REFERENCES `DOMINIO_TIPO_ACAO` (`ID`)
);

CREATE TABLE `PESSOA` (
`ID` INT NOT NULL AUTO_INCREMENT,
`NOME` VARCHAR(100),
`IDADE`VARCHAR(100),
`EMAIL` VARCHAR(100),
PRIMARY KEY(`ID`)
);

CREATE TABLE `MENTOR` (
`ID` INT NOT NULL AUTO_INCREMENT,
`FOTO` BLOB,
`DESCRICAO_EXPERIENCIA` VARCHAR(4000),
`ID_PESSOA` INT NOT NULL,
PRIMARY KEY(`ID`),
CONSTRAINT `FK_PESSOA_MENTOR` FOREIGN KEY (`ID_PESSOA`) 
REFERENCES `PESSOA` (`ID`)
);

CREATE TABLE `MENTORADO` (
`ID` INT NOT NULL AUTO_INCREMENT,
`FOTO` BLOB,
`DESCRICAO_EXPERIENCIA` VARCHAR(4000),
`ID_PESSOA` INT NOT NULL,
PRIMARY KEY(`ID`),
CONSTRAINT `FK_PESSOA_MENTORADO` FOREIGN KEY (`ID_PESSOA`) 
REFERENCES `PESSOA` (`ID`)
);

CREATE TABLE `USUARIO` (
`ID` INT NOT NULL AUTO_INCREMENT,
`NOME` VARCHAR(100),
`SENHA` VARCHAR(100),
`ID_MENTOR` INT NOT NULL,
`ID_MENTORADO` INT NOT NULL,
`ID_DOMINIO_STATUS_USUARIO` INT NOT NULL,
`ID_DOMINIO_TIPO_USUARIO` INT NOT NULL,
PRIMARY KEY(`ID`),
CONSTRAINT `FK_MENTOR` FOREIGN KEY (`ID_MENTOR`) 
REFERENCES `MENTOR` (`ID`),
CONSTRAINT `FK_MENTORADO` FOREIGN KEY (`ID_MENTORADO`) 
REFERENCES `MENTORADO` (`ID`),
CONSTRAINT `FK_DOMINIO_STATUS_USUARIO_USUARIO` FOREIGN KEY (`ID_DOMINIO_STATUS_USUARIO`) 
REFERENCES `DOMINIO_STATUS_USUARIO` (`ID`),
CONSTRAINT `FK_DOMINIO_TIPO_USUARIO_USUARIO` FOREIGN KEY (`ID_DOMINIO_TIPO_USUARIO`) 
REFERENCES `DOMINIO_TIPO_USUARIO` (`ID`)

);


CREATE TABLE `HABILIDADE_DESEJADA` (
`ID` INT NOT NULL AUTO_INCREMENT,
`ID_DOMINIO_HABILIDADES` INT NOT NULL,
`ID_MENTORADO` INT NOT NULL,
PRIMARY KEY(`ID`),
CONSTRAINT `FK_DOMINIO_HABILIDADES` FOREIGN KEY (`ID_DOMINIO_HABILIDADES`) 
REFERENCES `DOMINIO_HABILIDADES` (`ID`),
CONSTRAINT `FK_MENTORADO_HABILIDADE_DESEJADA` FOREIGN KEY (`ID_MENTORADO`) 
REFERENCES `MENTORADO`(`ID`)
);

CREATE TABLE `HABILIDADE_ITEM` (
`ID` INT NOT NULL AUTO_INCREMENT,
`ID_DOMINIO_HABILIDADES` INT NOT NULL,
`ID_DOMINIO_NIVEL_EXPERIENCIA` INT NOT NULL,
PRIMARY KEY(`ID`),
CONSTRAINT `FK_DOMINIO_HABILIDADES_HABILIDADE_ITEM` FOREIGN KEY (`ID_DOMINIO_HABILIDADES`) 
REFERENCES `DOMINIO_HABILIDADES` (`ID`),
CONSTRAINT `FK_DOMINIO_NIVEL_EXPERIENCIA_HABILIDADE_ITEM` FOREIGN KEY (`ID_DOMINIO_NIVEL_EXPERIENCIA`) 
REFERENCES `DOMINIO_NIVEL_EXPERIENCIA` (`ID`)
);

CREATE TABLE `HABILIDADE_MENTORADO` (
`ID` INT NOT NULL AUTO_INCREMENT,
`ID_HABILIDADE_ITEM` INT NOT NULL,
`ID_MENTORADO` INT NOT NULL,
PRIMARY KEY(`ID`),
CONSTRAINT `FK_HABILIDADE_ITEM_HABILIDADE_MENTORADO` FOREIGN KEY (`ID_HABILIDADE_ITEM`) 
REFERENCES `HABILIDADE_ITEM` (`ID`),
CONSTRAINT `FK_MENTORADO_HABILIDADE_MENTORADO` FOREIGN KEY (`ID_MENTORADO`) 
REFERENCES `MENTORADO` (`ID`)
);

CREATE TABLE `HABILIDADE_MENTOR` (
`ID` INT NOT NULL AUTO_INCREMENT,
`ID_HABILIDADE_ITEM` INT NOT NULL,
`ID_MENTORADO` INT NOT NULL,
PRIMARY KEY(`ID`),
CONSTRAINT `FK_HABILIDADE_ITEM_HABILIDADE_MENTOR` FOREIGN KEY (`ID_HABILIDADE_ITEM`) 
REFERENCES `HABILIDADE_ITEM` (`ID`),
CONSTRAINT `FK_MENTORADO_HABILIDADE_MENTOR` FOREIGN KEY (`ID_MENTORADO`) 
REFERENCES `MENTORADO` (`ID`)
);



CREATE TABLE `CONFIRMACAO_MENTORIA` (
`ID` INT NOT NULL AUTO_INCREMENT,
`ID_DOMINIO_STATUS_MENTORIA` INT NOT NULL,
PRIMARY KEY(`ID`),
CONSTRAINT `FK_DOMINIO_STATUS_MENTORIA_CONFIRMACAO_MENTORIA` FOREIGN KEY (`ID_DOMINIO_STATUS_MENTORIA`) 
REFERENCES `DOMINIO_STATUS_MENTORIA` (`ID`)
);

CREATE TABLE `ENVIO_EMAIL` (
`ID` INT NOT NULL AUTO_INCREMENT,
`TITULO` VARCHAR(100),
`ASSUNTO` VARCHAR(100),
`CONTEUDO` VARCHAR(4000),
`STATUS_ENVIO` NUMERIC(1,0),
`NUMERO_TENTATIVAS` INT,
`ID_DOMINIO_TIPO_EMAIL` INT NOT NULL,
PRIMARY KEY(`ID`),
CONSTRAINT `FK_DOMINIO_TIPO_EMAIL` FOREIGN KEY (`ID_DOMINIO_TIPO_EMAIL`) 
REFERENCES `DOMINIO_TIPO_EMAIL` (`ID`)
);

CREATE TABLE `AGENDAMENTO_MENTORIA` (
`ID` INT NOT NULL AUTO_INCREMENT,
`ID_ENVIO_EMAIL` INT NOT NULL,
`ID_CONFIRMACAO_MENTORIA` INT NOT NULL,
PRIMARY KEY(`ID`),
CONSTRAINT `FK_ENVIO_EMAIL` FOREIGN KEY (`ID_ENVIO_EMAIL`) 
REFERENCES `ENVIO_EMAIL` (`ID`),
CONSTRAINT `FK_CONFIRMACAO_MENTORIA` FOREIGN KEY (`ID_CONFIRMACAO_MENTORIA`) 
REFERENCES `CONFIRMACAO_MENTORIA` (`ID`)
);

CREATE TABLE `MENTORIA` (
`ID` INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(`ID`),
`ID_MENTORADO` INT NOT NULL,
`ID_MENTOR` INT NOT NULL,
`ID_AGENDAMENTO_MENTORIA` INT NOT NULL,
`ID_DOMINIO_TIPO_MENTORIA` INT NOT NULL,
CONSTRAINT `FK_MENTORADO_MENTORIA` FOREIGN KEY (`ID_MENTORADO`) 
REFERENCES `MENTORADO` (`ID`),
CONSTRAINT `FK_MENTOR_MENTORIA` FOREIGN KEY (`ID_MENTOR`) 
REFERENCES `MENTOR` (`ID`),
CONSTRAINT `FK_AGENDAMENTO_MENTORIA` FOREIGN KEY (`ID_AGENDAMENTO_MENTORIA`) 
REFERENCES `AGENDAMENTO_MENTORIA` (`ID`),
CONSTRAINT `FK_DOMINIO_TIPO_MENTORIA_MENTORIA` FOREIGN KEY (`ID_DOMINIO_TIPO_MENTORIA`) 
REFERENCES `DOMINIO_TIPO_MENTORIA` (`ID`)
);

CREATE TABLE `HISTORICO_MENTORIA` (
`ID` INT NOT NULL AUTO_INCREMENT,
`ID_HISTORICO` INT NOT NULL,
`ID_MENTORIA` INT NOT NULL,
PRIMARY KEY(`ID`),
CONSTRAINT `FK_HISTORICO_HISTORICO_MENTORIA` FOREIGN KEY (`ID_HISTORICO`) 
REFERENCES `HISTORICO` (`ID`),
CONSTRAINT `FK_MENTORIA_HISTORICO_MENTORIA` FOREIGN KEY (`ID_MENTORIA`) 
REFERENCES `MENTORIA` (`ID`)
);


INSERT INTO HEYORANGE.DOMINIO_TIPO_USUARIO
(DESCRICAO, FLAG_ATIVO, NUMERO_ORDEM)
VALUES
    ('admin', 1, 1),
    ('user', 1, 2)
;

INSERT INTO HEYORANGE.DOMINIO_STATUS_USUARIO
(DESCRICAO, FLAG_ATIVO, NUMERO_ORDEM)
VALUES
    ('ativo', 1, 1),
    ('bloqueado', 1, 2),
    ('inativo', 1, 3)
;

INSERT INTO HEYORANGE.DOMINIO_STATUS_MENTORIA
(DESCRICAO, FLAG_ATIVO, NUMERO_ORDEM)
VALUES
    ('agendada', 1, 1),
    ('confirmada', 1, 2),
    ('cancelada', 1, 3)
;

INSERT INTO HEYORANGE.DOMINIO_TIPO_EMAIL
(DESCRICAO, FLAG_ATIVO, NUMERO_ORDEM)
VALUES
    ('aviso', 1, 1),
    ('convite mentoria', 1, 2),
    ('notificacao de aceite', 1, 3)
;

INSERT INTO HEYORANGE.DOMINIO_HABILIDADES
(DESCRICAO, FLAG_ATIVO, NUMERO_ORDEM)
VALUES
    ('especialista em Springboot', 1, 1),
    ('especialista em API', 1, 2),
    ('especialista em Burnout', 1, 3)
;

INSERT INTO HEYORANGE.DOMINIO_NIVEL_EXPERIENCIA
(DESCRICAO, FLAG_ATIVO, NUMERO_ORDEM)
VALUES
    ('Trainee', 1, 1),
    ('Junior', 1, 2),
    ('Pleno', 1, 3),
    ('Senior', 1, 4)
;

INSERT INTO HEYORANGE.DOMINIO_TIPO_ACAO
(DESCRICAO, FLAG_ATIVO, NUMERO_ORDEM)
VALUES
    ('create', 1, 1),
    ('update', 1, 2),
    ('delete', 1, 3)
;

INSERT INTO HEYORANGE.DOMINIO_TIPO_MENTORIA
(DESCRICAO, FLAG_ATIVO, NUMERO_ORDEM)
VALUES
    ('bate papo', 1, 1),
    ('mentoria', 1, 2),
    ('ajuda em algum problema', 1, 3)
;





